
Run hello world test:
  image: marketsquare/robotframework-browser
  stage: test
  script:
    - robot -d Result Tests
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - logs
    reports:
      junit: logs/xunit.xml
