name: Jobs
on: 
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
jobs:
  this-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.MattiasITHS}}
      - name: Testspace push test content
        run: testspace "[${{ github.workflow }}/${{ github.job}}]./Tests/*.xml"
